### ISSUE TITLE
Is it completely free to use?

### ISSUE THREAD

**Issue by aninkina** [paraslamsong/osm_offline_download#1]
Hello I'am searching for free map api with offline mode.
1. Why is there a key property in widget  YetiTechOsm? 
2. Also how can be map api OSMMapBox.downloadOffline (osm + mapbox)? Is it totally free? 
3. I can't downoad your package with command [[flutter pub add osm_offline_download]]. There is a error: could not find package osm_offline_download at https://pub.dartlang.org.

**Comment by paraslamsong** [comment]
Dear aninkina,
Thank you for your concern, but the package is still in development, we are planning to use key for commercial use.
If you need some help, I can help you out. You can use [Flutter Map](https://pub.dev/packages/flutter_map) to use any kind of map.

Thank you
